Hw01 hello otus
KiriukhinD/hw-test pull request #1
Opened 2024-04-21 06:11 UTC by KiriukhinD

## Домашнее задание №1 «Hello, OTUS!»

### Чек-лист студента ([Что это?]))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?]
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?]-2)
- [ ] Я использовал `stringutil.Reverse`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?]
  - main.go ~12 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Используется `stringutil` - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-04-22 17:11 UTC, engineer-go requested changes

2024-04-22 17:11 UTC, engineer-go commented on hw01_hello_otus/go.mod
>  module github.com/fixme_my_friend/hw01_hello_otus
Дмитрий, добрый день, необходимо поправить путь к модулю. Пусть состоит из вашего хендла в github, названия репозитория и папки.

2024-04-22 17:58 UTC, KiriukhinD commented on hw01_hello_otus/go.mod
>  module github.com/fixme_my_friend/hw01_hello_otus
Добрый вечер,поправил путь к модулю.

2024-04-23 06:27 UTC, engineer-go approved these changes

2024-04-23 07:18 UTC, merged